apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-cgm-api
  namespace: fast-cgm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-cgm-api
  template:
    metadata:
      labels:
        app: fast-cgm-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: fast-cgm-api
          image: mauriquev/fast-cgm-api:2a8c6d71ffacd82041ad4cc953f508f57b4467bf
          envFrom:
          - secretRef:
              name: fast-cgm-db-credentials
          - secretRef:
              name: fast-cgm-dexcom-credentials
          ports:
          - containerPort: 8000

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
      