apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-cgm-api
  namespace: fast-cgm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-cgm-api
  template:
    metadata:
      labels:
        app: fast-cgm-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: fast-cgm-api
          image: mauriquev/fast-cgm-api:0c5e8f2c78f4b6736592d8fd9cd3e830512757af
          envFrom:
          - secretRef:
              name: fast-cgm-db-credentials
          - secretRef:
              name: fast-cgm-dexcom-credentials
          ports:
          - containerPort: 8000

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
      