apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-cgm-api
  namespace: fast-cgm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-cgm-api
  template:
    metadata:
      labels:
        app: fast-cgm-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: fast-cgm-api
          image: mauriquev/fast-cgm-api:IMAGE_TAG
          ports:
            - containerPort: 8000

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
      resources: []