apiVersion: v1
kind: Service
metadata:
  name: fast-cgm-server
  namespace: fast-cgm-api
spec:
  selector:
    app: fast-cgm-api
  ports:
    - port: 80         
      targetPort: 8000   
      protocol: TCP
  type: ClusterIP